<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User $user
 * @var array $widgets
 */

$plugins = $this->getHelperPluginManager();
$pageTitle = $plugins->get('pageTitle');

// TODO Restructure workflow for guest widgets.
$guestWidget = $plugins->get('guestWidget');

$this->htmlElement('body')->appendAttribute('class', 'guest account page');
?>

<h2><?= $this->siteSetting('guest_dashboard_label') ?: $this->setting('guest_dashboard_label') ?></h2>

<?= $this->messages() ?>

<?php foreach ($widgets as $widget): ?>
<div class="guest-widget">
    <?= $guestWidget($widget) ?>
</div>
<?php endforeach; ?>
