<?php
use Zend\Form\Element\Textarea;
?>
<?php echo $this->blockAttachmentsForm($block);?>
<?php if(isset($block)):
  $searchbar = $block->dataValue('searchbar');
else:
  $searchbar = 0;
endif;?>
<div class="field">
  <div class="field-meta">
      <label>Show searchbar</label>
      <a href="#" class="expand" aria-label="Expand" title="Expand"></a>
      <div class="collapsible">
        <div class="field-description">Show the searchbar</div>
      </div>
  </div>
  <div class="inputs">
      <input type="checkbox" class="" value="searchbar" <?php echo ($searchbar == 'searchbar' ? 'checked' : '') ?> name="o:block[__blockIndex__][o:data][searchbar]">
  </div>
</div>
<a href="#" class="expand" aria-label="Expand" title="Expand"><strong>Blocks</strong></a>
<div class="collapsible">
<p>
  This block will only appear when 3 images (attachments) are selected.
</p>

<hr />
<div class="field">
  <div class="field-meta">
      <label>Title block 1</label>
  </div>
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('title1')); ?>" name="o:block[__blockIndex__][o:data][title1]">
  </div>
</div>
<div class="field">
  <div class="field-meta">
      <label>Subtitle block 1</label>
  </div>
  <div class="inputs">
    <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('text1')); ?>" name="o:block[__blockIndex__][o:data][text1]">
  </div>
</div>
<div class="field">
  <div class="field-meta">
      <label>Link 1</label>
  </div>
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('link1')) ?>" name="o:block[__blockIndex__][o:data][link1]">
  </div>
</div>
<hr />
<div class="field">
  <div class="field-meta">
    <label>Title block 2</label>
  </div>
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('title2')); ?>" name="o:block[__blockIndex__][o:data][title2]">
  </div>
</div>
<div class="field">
  <div class="field-meta">
      <label>Subtitle block 2</label>
  </div>
  <div class="inputs">
    <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('text2')); ?>" name="o:block[__blockIndex__][o:data][text2]">
  </div>
</div>
<div class="field">
  <div class="field-meta">
      <label>Link 2</label>
  </div>
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('link2')) ?>" name="o:block[__blockIndex__][o:data][link2]">
  </div>
</div>
<hr />
<div class="field">
  <div class="field-meta">
      <label>Title block 3</label>
  </div>
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('title3')); ?>" name="o:block[__blockIndex__][o:data][title3]">
  </div>
</div>
<div class="field">
  <div class="field-meta">
      <label>Subtitle block 3</label>
  </div>
  <div class="inputs">
    <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('text3')); ?>" name="o:block[__blockIndex__][o:data][text3]">
  </div>
</div>
<div class="field">
  <div class="field-meta">
      <label>Link 3</label>
  </div>
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('link3')) ?>" name="o:block[__blockIndex__][o:data][link3]">
  </div>
</div>
<hr />
<div class="field">
  <div class="field-meta">
      <label>Title block 4</label>
  </div>
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('title4')); ?>" name="o:block[__blockIndex__][o:data][title4]">
  </div>
</div>
<div class="field">
  <div class="field-meta">
      <label>Subtitle block 4</label>
  </div>
  <div class="inputs">
    <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('text4')); ?>" name="o:block[__blockIndex__][o:data][text4]">
  </div>
</div>
<div class="field">
  <div class="field-meta">
      <label>Link 4</label>
  </div>
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('link4')) ?>" name="o:block[__blockIndex__][o:data][link4]">
  </div>
</div>
</div>
