  <div class="container">
    
    <div class="columns">
     
          <div class="column">
            <div class="card equal-height">         
                <h5 class="title is-6">
                  <?php echo $block->dataValue('title1');?>
                </h5>
                           
                <div class="card-content ">
                  <div class="content">
                    <?php echo $block->dataValue('text1');?>
                  </div>
                </div>
                <?php if($block->dataValue('link1') && $block->dataValue('linktext1')):?>
                <footer class="card-footer">
                  <a class="card-footer-item" href="<?php echo $block->dataValue('link1');?>">
                    <?php echo $block->dataValue('linktext1');?></a>
                  </footer>
                <?php endif;?>
            </div>
          </div>

          <div class="column spotlight">
            <div class="card equal-height">         
                <h5 class="title is-6">
                  <?php echo $block->dataValue('title2');?>
                </h5>
                           
                <div class="card-content ">
                  <div class="content">
                    <?php echo $block->dataValue('text2');?>
                  </div>
                </div>
                <?php if($block->dataValue('link2') && $block->dataValue('linktext2')):?>
                  <footer class="card-footer">
                  <a class="card-footer-item" href="<?php echo $block->dataValue('link2');?>">
                    <?php echo $block->dataValue('linktext2');?></a>
                  </footer>
                <?php endif;?>
                <div style="display:flex;justify-content: center;" class="">
                <?php foreach($attachments as $at):?>
                  <?php
                    $media = $at->media();
                    $url = $media->thumbnailUrl('medium');                  
                  ?>
                  <img style="width:40%;padding:0 1rem;display:inline-block;" src="<?php echo $url;?>">
                <?php endforeach;?>  
                </div>
            </div>           
          </div>
    </div>
</div>