<?php
use Zend\Form\Element\Textarea;
?>
<p>
 Choose the thumbnails that will appear underneath the spotlight text.
</p>
<?php echo $this->blockAttachmentsForm($block);?>

<input type="hidden" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('title')); ?>" name="o:block[__blockIndex__][o:data][title]">

<h4>Title website</h4>
<div class="field">
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('title1')); ?>" name="o:block[__blockIndex__][o:data][title1]">
  </div>
</div>
<h4>Text about website</h4>
<?php
  $textarea = new Textarea("o:block[__blockIndex__][o:data][text1]");
  $textarea->setAttribute('class', 'block-html full wysiwyg');
  if ($block) {
      $textarea->setAttribute('value', $block->dataValue('text1'));
  }
  echo $this->formRow($textarea);
?>
<div class="field">
  <div class="field-meta">
      <label>Link 1</label>
  </div>
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('link1')) ?>" name="o:block[__blockIndex__][o:data][link1]">
  </div>
</div>
<div class="field">
  <div class="field-meta">
      <label>Link text 1</label>
  </div>
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('linktext1')) ?>" name="o:block[__blockIndex__][o:data][linktext1]">
  </div>
</div>
<hr />
<h4>Title spotlight</h4>
<div class="field">
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('title2')); ?>" name="o:block[__blockIndex__][o:data][title2]">
  </div>
</div>
<h4>Text spotlight</h4>
<?php
  $textarea = new Textarea("o:block[__blockIndex__][o:data][text2]");
  $textarea->setAttribute('class', 'block-html full wysiwyg');
  if ($block) {
      $textarea->setAttribute('value', $block->dataValue('text2'));
  }
  echo $this->formRow($textarea);
?>
<div class="field">
  <div class="field-meta">
      <label>Link 2</label>
  </div>
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('link2')) ?>" name="o:block[__blockIndex__][o:data][link2]">
  </div>
</div>
<div class="field">
  <div class="field-meta">
      <label>Link text 2</label>
  </div>
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('linktext2')) ?>" name="o:block[__blockIndex__][o:data][linktext2]">
  </div>
</div>
