<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2017-2021
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var string $tag
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
?>
<?php $type = "";?>
<?php $template = $resource->resourceTemplate();?>
<?php if($template):?>
<?php $type = $template->label();?>
<?php endif;?>

<div class="columns">
    <?php if($type == "Manuscript"):?>
    <div class="column is-2">
        <div class="resource-thumbnail">
            <?php $media = $resource->primaryMedia(); ?>
            <?php if($media):?>
                <a href="<?php echo $resource->url();?>">
                    <?= $this->thumbnail($media, 'square', ['title' => $media->displayTitle(), 'alt' => $media->mediaType() . ' thumbnail']);?>
                </a>
            <?php else:?>
              <div class="placeholder"></div>  
            <?php endif;?>
        </div>
    </div>
    <?php endif;?>    
    <div class="column">            
        <div class="resource-metadata">
            <h4 class="title is-6"><a href="<?= $resource->url() ?>"><?= $resource->displayTitle() ?></a></h4>           
            
            <?php if($type):?>
                <h5 class="subtitle is-7" style="font-weight:300;text-transform:uppercase;color:#cc6634;font-size:0.75rem;"><?php echo $type;?></h5>
            <?php endif;?>    
            
           
                <?php if($resource->value('alamire:originGeneral')):?>  
                    <div class="columns" style="padding-bottom:0.5rem">                 
                        <div class="column is-3" style="padding-bottom:0.5rem;padding-top:0rem;">
                            <strong>Origin</strong>
                        </div>
                        <div class="column is-7" style="padding-bottom:0.5rem;padding-top:0rem;">
                            <?php echo $resource->value('alamire:originGeneral')->asHtml();?>
                        </div>
                    </div>       
                <?php endif;?>
                <?php if($resource->value('alamire:dateCreated')):?>  
                    <div class="columns" style="padding-bottom:0.5rem">                 
                        <div class="column is-3" style="padding-bottom:0.5rem;padding-top:0rem;">
                            <strong>Date / Date range</strong>
                        </div>
                        <div class="column is-7" style="padding-bottom:0.5rem;padding-top:0rem;">
                            <?php echo $resource->value('alamire:dateCreated')->asHtml();?>
                        </div>
                    </div>       
                <?php endif;?>
                <?php if($resource->value('alamire:holdingInstitution')):?>  
                    <div class="columns" style="padding-bottom:0.5rem">                 
                        <div class="column is-3" style="padding-bottom:0.5rem;padding-top:0rem;">
                            <strong>Holding institution</strong>
                        </div>
                        <div class="column is-7" style="padding-bottom:0.5rem;padding-top:0rem;">
                            <?php echo $resource->value('alamire:holdingInstitution')->asHtml();?>
                        </div>
                    </div>       
                <?php endif;?>
                <?php if($resource->value('alamire:creator_display')):?>  
                    <div class="columns" style="padding-bottom:0.5rem">                 
                        <div class="column is-3" style="padding-bottom:0.5rem;padding-top:0rem;">
                            <strong>Composer</strong>
                        </div>
                        <div class="column is-7" style="padding-bottom:0.5rem;padding-top:0rem;">
                        <?php                        
                            $cites = $resource->value('alamire:creator_display',array('all' => true));
                            $sort_cites = array();
                            foreach($cites as $cite):
                                if(str_contains($cite->asHtml(),"$$")):
                                    $cite = explode(" $$ ",$cite->asHtml());    
                                    $comps = trim($cite[0]);
                                    $comps = explode(" (",$comps);
                                    if(!empty($comps[1])):
                                        $type = $comps[1];
                                        if($type == "credited)"):
                                            $comp = $comps[0];
                                        elseif($type == "stylistic)"):
                                            $comp = "[".$comps[0]."]";
                                        elseif($type == "contested)"):
                                            $comp = "?".$comps[0];
                                        endif;
                                    else:      
                                        $comp = $comps[0];
                                    endif;   
                                    $sort_cites[trim($cite[1])] = $comp;
                                else:
                                    echo $cite->asHtml();      
                                endif;  
                            endforeach;
                            ksort($sort_cites);    
                            echo reset($sort_cites);
                        ?>
                        </div>
                    </div>       
                <?php endif;?>
                <?php if($resource->value('alamire:voices')):?>  
                    <div class="columns" style="padding-bottom:0.5rem">                 
                        <div class="column is-3" style="padding-bottom:1rem;padding-top:0rem;">
                            <strong>Voices</strong>
                        </div>
                        <div class="column is-7" style="padding-bottom:1rem;padding-top:0rem;">
                            <?php echo $resource->value('alamire:voices')->asHtml();?>
                        </div>
                    </div>       
                <?php endif;?>

                <?php if($resource->value('alamire:category')):?>  
                    <div class="columns" style="padding-bottom:0.5rem">                 
                        <div class="column is-3" style="padding-bottom:1rem;padding-top:0rem;">
                            <strong>Category</strong>
                        </div>
                        <div class="column is-7" style="padding-bottom:1rem;padding-top:0rem;">
                            <?php echo $resource->value('alamire:category')->asHtml();?>
                        </div>
                    </div>       
                <?php endif;?>

                <?php if ($description = $resource->displayDescription()): ?>
                <div class="columns" style="padding-bottom:0.5rem;padding-top:0.5rem;">                 
                    <div class="column is-12" style="padding-bottom:1rem;padding-top:0rem;">
                        <?= $description ?>
                    </div>
                </div>
                
            <?php endif; ?>
        </div>
    </div>
</div>
