<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$pageTitle = $plugins->get('pageTitle');
?>

<?= $pageTitle($translate('Authentication error')) ?>

<div class="guest-anonymous guest-auth-error">

    <?= $this->messages() ?>

    <p>
        <?= $translate('An error occurred during the authentication via a third party authenticator.') ?>
    </p>
    <p>
        <?= $translate('Contact your administrator for more information.') ?>
    </p>

</div>
