<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Form\UserForm $form
 */

$plugins = $this->getHelperPluginManager();
$trigger = $plugins->get('trigger');
$setting = $plugins->get('setting');
$translate = $plugins->get('translate');
$pageTitle = $plugins->get('pageTitle');
$siteSetting = $plugins->get('siteSetting');
$htmlElement = $plugins->get('htmlElement');

$htmlElement('body')->appendAttribute('class', 'guest register');
$form->prepare();
?>

<?= $pageTitle($siteSetting('guest_register_text') ?: ($setting('guest_register_text') ?: $translate('Register'))) ?>

<div class="guest-anonymous guest-register">

    <?= $this->messages() ?>

    <div><?= $siteSetting('guest_capabilities') ?: ($setting('guest_capabilities')) ?></div>

    <?= $this->form()->openTag($form) ?>
        <?= $this->formCollection($form, false) ?>
        <?php $trigger('view.add.form.after'); ?>
        <div id="page-actions">
            <button type="submit"><?= $translate('Register') ?></button>
        </div>
    <?= $this->form()->closeTag() ?>

    <?php $trigger('view.add.after'); ?>

</div>
