<?php
$url = $this->serverUrl(true);
//echo $url;
echo $this->resource();
if (strpos($url, 'page/home') !== false || $url == "https://idemdatabase.org/") {
    $home = true;
}else{
  $home = false;
}
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle()->setSeparator(' | ');
if($home):
  $this->headTitle("Integrated Database for Early Music - Alamire Foundation");
else:
  $this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
endif;  
$this->headLink()->prependStylesheet($this->assetUrl('css/style.min.css'));
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/slick.js'));
$this->headScript()->prependFile($this->assetUrl('js/readmore.js'));
$this->headScript()->prependFile($this->assetUrl('js/clamp.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php //var_dump($this->basePath());?>
        <meta name="description" content="The Integrated for Early Music of the Alamire Foundation provides high resolution images and detailed descriptions of early music sources, especially (with composers) from the Low Countries">
        <meta name="author" content="Alamire Foundation">
        <meta name="keywords" content="Early Music, Manuscript, Plainchant, Polyphony, Carillon, Low Countries">
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <link href='//fonts.googleapis.com/css?family=Dosis:400,500,600,700' rel='stylesheet' type='text/css'>
        <script src="https://kit.fontawesome.com/582fb8c29f.js" crossorigin="anonymous"></script><link href='//fonts.googleapis.com/css?family=Dosis:400,500,600,700' rel='stylesheet' type='text/css'>
        <script src="https://unpkg.com/colcade@0/colcade.js"></script>
    </head>
    <?php echo $this->htmlElement('body'); ?>
    <?php echo $userBar; ?>
    <header>
      <div class="container">
        <div class="columns">
          <div class="column is-3 left-nav">
            <a class="navbar-item" href="<?php echo $site->url(); ?>" style="padding:1rem 0 0 0;">
              <div class="logo-1">
              <?php if ($this->themeSetting('logo')): ?>
                  <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                  <br>Alamire<br>Foundation
                  <?php else: ?>
                  <?php echo $escape($siteTitle); ?>
              <?php endif; ?>
              </div>              
            </a>        
          </div>
          <div class="column">
            <div id="site-title-text">
              <a href="<?php echo $site->url();?>">IDEM</a>
             <div id="description">Integrated Database for Early music</div>
            </div>  
          </div>
        </div>
      </div>      
    </header>
    <section class="section">
      <div class="container">
        <div class="columns">
          <div class="column is-3 left-nav filter-nav">
          <?php
            echo $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => $this->themeSetting('nav_depth') - 1
            ]);
          ?>
          </div>
          <div class="column"><?php echo $this->content; ?></div>                
        </div>
      </div>
    </section>
    <footer class="footer">
      <div class="container">
        <div class="content">
          <?php if ($footerContent = $this->themeSetting('footer')): ?>
          <?php echo $footerContent; ?>
          <?php else: ?>
              <?php echo $this->translate('Powered by Omeka S'); ?>
          <?php endif; ?>
        </div>
      </div>
    </footer>

    <div class="search-menu modal">
      <div class="modal-background"></div>
        <div class="modal-content">
          <?php echo $this->partial('common/search-form'); ?>
        </div>
        <button class="search-menu-close modal-close is-large"></button>
     </div>

     <div class="burger-menu modal">
       <div class="modal-background"></div>
         <div class="modal-content">
           <!-- Any other Bulma elements you want -->
           <?php echo $this->partial('common/search-form'); ?>
           <?php
             echo $site->publicNav()->menu()->renderMenu(null, [
                 'maxDepth' => $this->themeSetting('nav_depth') - 1
             ]);
           ?>
         </div>
         <button class="burger-menu-close modal-close is-large"></button>
      </div>   
  </body>
  <script>
  $(document).ready(function() {
    // Check for click events on the navbar burger icon
    $(".navbar-burger").click(function() {
        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        //$(".navbar-burger").toggleClass("is-active");
        $(".burger-menu").toggleClass("is-active");
    });

    $("#showSearch").click(function() {
    $(".search-menu").addClass("is-active");
    });

    $(".search-menu-close").click(function() {
       $(".search-menu").removeClass("is-active");
    });
    $(".burger-menu-close").click(function() {
       $(".burger-menu").removeClass("is-active");
    });
    $(".terms-close").click(function() {
       $(".terms-modal").toggleClass("is-active");
    });

    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
     m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
     })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

     ga('create', 'UA-103097674-1', 'auto');
     ga('send', 'pageview');

  });
  </script>
</html>
