<?php
$url = $this->serverUrl(true);
$item = "";
$type = "";
//echo $url;
$meta_description = "The Integrated for Early Music of the Alamire Foundation provides high resolution images and detailed descriptions of early music sources, especially (with composers) from the Low Countries";
$meta_keywords = "Early Music, Manuscript, Plainchant, Polyphony, Carillon, Low Countries";
if (strpos($url, 'page/home') !== false || $url == "https://idemdatabase.org/") {
  $home = true;
} else {
  $home = false;
  if (strpos($url, 'page/userguide')):
    $meta_description = "Learn how to use the Integrated Database for Early Music in this quick user guide";
  elseif ("page/bibliography"):
    $meta_description = "Browse the exhaustive list of bibliographical references used in Integrated Database for Early Music";
  elseif ("page/terms"):
    $meta_description = "Read about our Terms & Conditions on the use and citation of the images and metadata of the Integrated Database for Early Music.";
  endif;

  if (strpos($url, "item/")):
    $parts = explode("/", $url);
    $id = end($parts);
    $query = 'property[0][joiner]=and&property[0][property]=339&property[0][type]=eq&property[0][text]=' . $id;
    parse_str($query, $query);
    $item = $this->api()->searchOne('items', $query);
    $item = $item->getContent();

    if ($item):
      $template = $item->resourceTemplate();
      if ($template):
        $type = $template->label();
      endif;
      if ($type == "Manuscript"):
        $meta_description = "Browse digitally through manuscript " . $item->displayTitle() . " in the Integrated Database for Early Music and discover more about the material, origin and content of the manuscript.";
        $values = $item->value("alamire:formatGeneralDisplay", array("all" => true));
        $values2 = $item->value("alamire:catergory", array("all" => true));
        $values = array_merge($values, $values2);
        $values[] = $item->value("alamire:originGeneral");
        $values[] = $item->value("alamire:dateCentury");
        $values = array_filter($values);
        $values = implode(",", $values);
        $meta_keywords = "Early music,Manuscript," . $values;
      elseif ($type == "Composition"):
        $meta_description = "View the composition " . $item->value("alamire:creator") . " - " . $item->displayTitle() . " in our digital sources and discover more about its authorship, structure and context.";
        $values = $item->value("alamire:creator", array("all" => true));
        $values[] = $item->value("alamire:category");
        $values[] = $item->value("alamire:genre");
        $values2 = $item->value("alamire:alamire:alternativeTitle", array("all" => true));
        $values = array_merge($values, $values2);
        $values = array_filter($values);
        $values = implode(",", $values);
        $meta_keywords = "Early music,Manuscript," . $values;
      endif;
    endif;
  endif;
}
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
if ($item):
  $template = $item->resourceTemplate();
  if ($template):
    if ($template->label() == "Compostion"):
      $this->headTitle($template->label() . ": " . $item->value("alamire:creator") . " - " . $item->displayTitle() . " | Integrated Database for Early Music - Alamire Foundation")->setSeparator(' | ');
    else:
      $this->headTitle($template->label() . ": " . $item->displayTitle() . " | Integrated Database for Early Music - Alamire Foundation")->setSeparator(' | ');
    endif;
  else:
    $this->headTitle($item->displayTitle() . " | Integrated Database for Early Music - Alamire Foundation")->setSeparator(' | ');
  endif;
else:
  $this->headTitle("Integrated Database for Early Music - Alamire Foundation")->setSeparator(' | ');
endif;
$this->headLink()->prependStylesheet($this->assetUrl('css/style.min.css?v=1.0'));
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/slick.js'));
$this->headScript()->prependFile($this->assetUrl('js/readmore.js'));
$this->headScript()->prependFile($this->assetUrl('js/clamp.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>

<head>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle(); ?>
  <meta name="description" content="<?php echo $meta_description; ?>">
  <meta name="author" content="Alamire Foundation">
  <meta name="keywords" content="<?php echo $meta_keywords; ?>">
  <?php echo $this->headLink(); ?>
  <?php echo $this->headStyle(); ?>
  <?php echo $this->headScript(); ?>
  <link href='//fonts.googleapis.com/css?family=Dosis:400,500,600,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.6.0/css/all.min.css" integrity="sha512-ykRBEJhyZ+B/BIJcBuOyUoIxh0OfdICfHPnPfBy7eIiyJv536ojTCsgX8aqrLQ9VJZHGz4tvYyzOM0lkgmQZGw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<?php echo $this->htmlElement('body'); ?>
<?php echo $userBar; ?>
<header>
  <section class="section header-section">
    <div class="container">
      <div class="columns">
        <div class="column is-3 left-nav">
          <a class="navbar-item" href="<?php echo $site->url(); ?>" style="padding:1rem 0 0 0;">
            <div class="logo-1">
              <?php if ($this->themeSetting('logo')): ?>
                <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                <br>Alamire<br>Foundation
              <?php else: ?>
                <?php echo $escape($siteTitle); ?>
              <?php endif; ?>
            </div>
          </a>
        </div>
        <div class="column right-section-nav">
          <div id="site-title-text">
            <a href="<?php echo $site->url(); ?>">IDEM</a>
            <div id="description">Integrated Database for Early music</div>
          </div>
          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
      </div>
    </div>
  </section>
</header>
<div class="scroll-to-top-button">
  <svg class="svg-inline--fa fa-angle-top fa-lg" data-prefix="fas" data-icon="angle-top" role="img" viewBox="0 0 256 512" fill="none" xmlns="http://www.w3.org/2000/svg" data-fa-i2svg>
    <path fill="#ffffff" d="M201.4 137.4c12.5-12.5 32.8-12.5 45.3 0l160 160c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L224 205.3 86.6 342.6c-12.5 12.5-32.8 12.5-45.3 0s-12.5-32.8 0-45.3l160-160z" />
  </svg>
</div>
<section class="section">
  <div class="container">
    <div class="columns is-desktop">
      <div class="column is-3-desktop left-nav filter-nav">
        <?php
        echo $site->publicNav()->menu()->renderMenu(null, [
          'maxDepth' => $this->themeSetting('nav_depth') - 1
        ]);
        ?>
      </div>
      <div class="column"><?php echo $this->content; ?></div>
    </div>
  </div>
</section>
<footer class="footer">
  <div class="container">
    <div class="content">
      <?php if ($footerContent = $this->themeSetting('footer')): ?>
        <?php echo $footerContent; ?>
      <?php else: ?>
        <?php echo $this->translate('Powered by Omeka S'); ?>
      <?php endif; ?>
    </div>
  </div>
</footer>

<div class="search-menu modal">
  <div class="modal-background"></div>
  <div class="modal-content">
    <?php echo $this->partial('common/search-form'); ?>
  </div>
  <button class="search-menu-close modal-close is-large"></button>
</div>

<div class="burger-menu modal">
  <div class="modal-background"></div>
  <div class="modal-content">
    <!-- Any other Bulma elements you want -->
    <?php
    echo $site->publicNav()->menu()->renderMenu(null, [
      'maxDepth' => $this->themeSetting('nav_depth') - 1
    ]);
    ?>
  </div>
  <div class="logo-1">
    <?php if ($this->themeSetting('logo')): ?>
      <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
      <br>Alamire<br>Foundation
    <?php else: ?>
      <?php echo $escape($siteTitle); ?>
    <?php endif; ?>
  </div>
  <button class="burger-menu-close modal-close is-large"></button>
</div>
<script>
  $(document).ready(function() {
    // Check for click events on the navbar burger icon
    $(".navbar-burger").click(function() {
      // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
      //$(".navbar-burger").toggleClass("is-active");
      $(".burger-menu").toggleClass("is-active");
      $(".page").addClass("pageFixed");
    });

    $("#showSearch").click(function() {
      $(".search-menu").addClass("is-active");
    });

    $(".search-menu-close").click(function() {
      $(".search-menu").removeClass("is-active");
    });
    $(".burger-menu-close").click(function() {
      $(".burger-menu").removeClass("is-active");
      $(".page").removeClass("pageFixed");
    });
    $(".terms-close").click(function() {
      $(".terms-modal").toggleClass("is-active");
    });

    $(".scroll-to-top-button").on("click", function() {
      $("body, html").animate({
        scrollTop: 0
      }, 800);
    });

    $('ul.navigation a[href]').each(function() {
      if ($(this).attr('href') === 'https://www.alamirefoundation.org/') {
        $(this).attr('target', '_blank');
      }
    });

    (function(i, s, o, g, r, a, m) {
      i['GoogleAnalyticsObject'] = r;
      i[r] = i[r] || function() {
        (i[r].q = i[r].q || []).push(arguments)
      }, i[r].l = 1 * new Date();
      a = s.createElement(o),
        m = s.getElementsByTagName(o)[0];
      a.async = 1;
      a.src = g;
      m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-103097674-1', 'auto');
    ga('send', 'pageview');

  });
</script>
</body>

</html>