<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.min.css'));
//$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
//$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/slick.js'));
$this->headScript()->prependFile($this->assetUrl('js/clamp.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <link href='//fonts.googleapis.com/css?family=Dosis:400,500,600,700' rel='stylesheet' type='text/css'>
        <script src="https://kit.fontawesome.com/582fb8c29f.js" crossorigin="anonymous"></script><link href='//fonts.googleapis.com/css?family=Dosis:400,500,600,700' rel='stylesheet' type='text/css'>
        <script src="https://unpkg.com/colcade@0/colcade.js"></script>
    </head>

    <?php echo $this->htmlElement('body'); ?>
    <?php echo $userBar; ?>
    <header>
        <nav class="navbar is-white" role="navigation" aria-label="main navigation">
          <div class="container">
          <div class="navbar-brand">
            <a class="navbar-item" href="<?php echo $site->url(); ?>">
              <div class="logo-1">
              <?php if ($this->themeSetting('logo')): ?>
                  <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                  <br>Alamire<br>Foundation
                  <?php else: ?>
                  <?php echo $escape($siteTitle); ?>
              <?php endif; ?>
              </div>              
            </a>

            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
          </div>
          <div class="navbar-menu">
            <div class="navbar-start">

            </div>
            <div class="navbar-end">
              <div class="navbar-item">
                <?php
                  echo $site->publicNav()->menu()->renderMenu(null, [
                      'maxDepth' => $this->themeSetting('nav_depth') - 1
                  ]);
                ?>
              </div>
               <div class="navbar-item">
                 <button class="button is-primary is-light" id="showSearch">
                    <span class="icon is-small">
                      <i class="fas fa-search"></i>
                    </span>
                  </button>
                </div>
             </div>
          </div>
        </div>
      </nav>

    </header>
    <div class="container">
      <div class="columns">
        <div class="column is-2 left-nav">
        <?php
          echo $site->publicNav()->menu()->renderMenu(null, [
              'maxDepth' => $this->themeSetting('nav_depth') - 1
          ]);
        ?>
        </div>
        <div class="column"><?php echo $this->content; ?></div>                
      </div>
    </div>
    
    <footer class="footer">
      <div class="container">
        <div class="content">
          <?php if ($footerContent = $this->themeSetting('footer')): ?>
          <?php echo $footerContent; ?>
          <?php else: ?>
              <?php echo $this->translate('Powered by Omeka S'); ?>
          <?php endif; ?>
        </div>
      </div>
    </footer>

    <div class="search-menu modal">
      <div class="modal-background"></div>
        <div class="modal-content">
          <?php echo $this->partial('common/search-form'); ?>
        </div>
        <button class="search-menu-close modal-close is-large"></button>
     </div>

     <div class="burger-menu modal">
       <div class="modal-background"></div>
         <div class="modal-content">
           <!-- Any other Bulma elements you want -->
           <?php echo $this->partial('common/search-form'); ?>
           <?php
             echo $site->publicNav()->menu()->renderMenu(null, [
                 'maxDepth' => $this->themeSetting('nav_depth') - 1
             ]);
           ?>
         </div>
         <button class="burger-menu-close modal-close is-large"></button>
      </div>
  </body>
  <script>
  $(document).ready(function() {
    // Check for click events on the navbar burger icon
    $(".navbar-burger").click(function() {
        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        //$(".navbar-burger").toggleClass("is-active");
        $(".burger-menu").toggleClass("is-active");
    });

    $("#showSearch").click(function() {
    $(".search-menu").addClass("is-active");
    });

    $(".search-menu-close").click(function() {
       $(".search-menu").removeClass("is-active");
    });
    $(".burger-menu-close").click(function() {
       $(".burger-menu").removeClass("is-active");
    });
  });
  </script>
</html>
