<?php
  $url = '';
  if($attachments):
    $media = $attachments[0]->media();

    $url = '';
    if($media):
      $url = $media->thumbnailUrl('large');
      $url = str_replace('http:', '', $url);
    endif;
  endif;
?>
<?php if($url):?>
<section class="hero is-primary is-medium is-bold" style="background:url(<?php echo $url;?>) no-repeat center center;background-size: cover;">
<?php else:?>
<section class="hero is-primary is-medium is-bold">
<?php endif;?>
  <div class="hero-body">
    <div class="container">
      <?php if($block->dataValue('sec_title')):?>
         <h2 class="subtitle is-size-6"><?php echo $block->dataValue('sec_title');?></h2>
      <?php endif;?>
      <h1 class="title is-family-secondary is-1"><?php echo $block->dataValue('title');?></h1>
      <div class="hero-text is-size-5">
        <?php echo $block->dataValue('text');?>
        <div class="link">
          <a class="button is-white is-outlined" href="<?php echo $block->dataValue('link');?>">
            <span><?php echo $block->dataValue('link_text');?></span>
            <span class="icon is-small">
              <i class="fas fa-angle-right"></i>
            </span>
          </a>
        </div>
      </div>
    </div>
   </div>
 </section>
