<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$helper = $this->plugin('Custom');
$labelInfo = $this->setting('property_label_information');
$firstextra = true;

$auth = false;
if($this->identity()):          
  $auth = true;  
endif;
?>

<?php foreach ($templateProperties as $term => $property): ?>
  <?php
  if($property->isPrivate()):
    continue;
  endif;
  $comment = $property->alternateComment();
  $propertyData = '';
  if(isset($values[$property->property()->term()])):
    $propertyData = $values[$property->property()->term()];
  else:
    continue;
  endif;

  if(isset($values["alamire:furtherBibliography"]) && isset($values["alamire:bibliographicCitation"]) && $property->property()->term() == "alamire:bibliographicCitation"):
    //if both bibliographies are present add an extran subtitle (in comment)
    $comment = "Bibliography";
  elseif($property->property()->term() == "alamire:bibliographicCitation"):
    //if not change select bibliography to bibliography
    $propertyData['alternate_label'] = "Bibliography";
    $comment = "";  
  endif;
   
  if($propertyData['property']->term() == "alamire:thumbnail" || $propertyData['alternate_label'] == "Manuscript Label"  || $propertyData['alternate_label'] == "Chant Label"):
    continue;
  endif;  
  ?>
  <?php if($comment == "extra" && $firstextra):?>
   
    <div class="columns extra-block" style="padding-top:1rem;padding-bottom:2rem;">
      <div class="column is-12">        
        <div><a class="extra-button button is-primary is-small is-outlined" href="#firstextra">
          <span class="icon">
          <i class="fa fa-list"></i>
          </span>
          <span>Detailed information</span></a></div>
      </div>
    </div>
        <div class="extra">
       
  <?php $firstextra = false;?>
  <?php endif; ?>
  <?php if($comment != "extra" && !$firstextra):?>
    
    </div>
    
  <?php $firstextra = true;?>
  <?php endif; ?>
  <?php if($comment != "extra" && $comment):?>
    <div class="columns is-12"> 
      <div class="column">
        <h4 class="has-text-weight-semibold is-6 section-head" style="margin-top:1rem;"><?php echo $comment;?></h4>
      </div>
    </div>
  <?php endif; ?>
  <?php
    $style="";$extra_class="";
    $alt_class="";
    if ($propertyData['alternate_label']):
      if($propertyData['alternate_label'] == "Inventory" || $propertyData['alternate_label'] == "Audio" || $propertyData['alternate_label'] == "Bibliography"  || $propertyData['alternate_label'] == "Archival record"):
        $extra_class="section-head";
        $style="padding-top:1rem;";
      endif;
      
      if(!str_contains($propertyData['alternate_label'],"title")):
        $alt_class = $propertyData['alternate_label'];
      endif;
    endif;
  ?>       
  <div class="columns <?php echo $alt_class; ?>" style="<?php echo $style;?>">  
    <div class="column is-one-fifth">
      
      <h5 class="has-text-weight-semibold is-6 <?php echo $extra_class;?>">
      <?php if ($propertyData['alternate_label']): ?>
      <?php echo $escape($propertyData['alternate_label']); ?>
      <?php else: ?>
      <?php echo $escape($translate($propertyData['property']->label())); ?>
      <?php endif; ?>
      <?php if ('term' === $labelInfo): ?>
      <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
      <?php elseif ('vocab' === $labelInfo): ?>
      <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
      <?php endif; ?>
      </h5>
    </div>
    <div class="column is-four-fifths <?php echo $alt_class; ?>-items">
      <?php if(($propertyData['property']->term() == "alamire:relatedComposition") || $propertyData['property']->term() == "alamire:description" || $propertyData['property']->term() == "alamire:bibliographicCitation" || $propertyData['property']->term() == "alamire:furtherBibliography"):?>
        <div class="values text">
      <?php else:?>
        <div class="values">
      <?php endif;?>  
      <?php foreach ($propertyData['values'] as $value): ?>
          <?php
          $valueType = $value->type();
          $class = ['value'];
          if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
              $class[] = 'resource';
              $class[] = $escape($value->valueResource()->resourceName());
          } elseif ('uri' == $valueType) {
              $class[] = 'uri';
          }
          if (!$value->isPublic()) {
              $class[] = 'private';
          }
          ?>

          <?php if($propertyData['property']->term() == 'alamire:holdingInstitution'):?>  
              <div style="margin-bottom:0.5rem;"><?php echo $value->asHtml();?></div>
          <?php elseif($propertyData['property']->term() == 'alamire:formatGeneral'):?>   
            <?php if($value->asHtml() == "codex (other)"):?>   
              <div style="margin-bottom:0.5rem;"><?php echo 'codex';?></div>   
            <?php else: ?>
              <div style="margin-bottom:0.5rem;"><?php echo $value->asHtml();?></div>
            <?php endif;?>
          <?php elseif($propertyData['property']->term() == 'alamire:creator_display'):?>
            <?php 
              if($values['alamire:creator_display']['values']):
                $cites = $values['alamire:creator_display']['values'];
                $sort_cites = array();
                foreach($cites as $cite):
                  if(str_contains($cite->asHtml(),"$$")):
                    $cite = explode(" $$ ",$cite->asHtml());     
                    $sort_cites[trim($cite[1])] = $cite[0];
                  else:
                    echo $cite->asHtml();  
                  endif;  
                endforeach;
                ksort($sort_cites);  
                foreach($sort_cites as $cite):        
                  $comps = trim($cite);
                  $comps = explode(" (",$comps);
                  if(!empty($comps[1]) && $comps[1] != ")"):
                      $type = $comps[1];
                      if($type == "credited)"):
                        $comp = $comps[0]." (".$comps[1];
                      elseif($type == "stylistic)"):
                        $comp = "[".$comps[0]."] (".$comps[1];
                      elseif($type == "contested)"):
                        $comp = "?".$comps[0]." (".$comps[1];
                      endif;
                  else:      
                    $comp = $comps[0];
                  endif;  
                  echo '<div style="margin-bottom:0.5rem;">'.$comp."</div>";                    
                endforeach;                      
              endif;
              $values['alamire:creator_display']['values'] = "";
            ?>
          <?php elseif($propertyData['property']->term() == 'alamire:arranger_display'):?>
            <?php 
              if($values['alamire:arranger_display']['values']):
                $cites = $values['alamire:arranger_display']['values'];
                $sort_cites = array();
                foreach($cites as $cite):
                  if(str_contains($cite->asHtml(),"$$")):
                    $cite = explode(" $$ ",$cite->asHtml());     
                    $sort_cites[trim($cite[1])] = $cite[0];
                  else:
                    echo $cite->asHtml();  
                  endif;  
                endforeach;
                ksort($sort_cites);  
                foreach($sort_cites as $cite):        
                  echo '<div style="margin-bottom:0.5rem;">'.trim($cite)."</div>";                    
                endforeach;                      
              endif;
              $values['alamire:arranger_display']['values'] = "";
            ?>  
          <?php elseif($propertyData['property']->term() == 'alamire:relatedArchivalRecord'):?>
            <?php 
              $archive = explode(" $$ ",$value->asHtml());                
              if(!empty($archive[2])):    
                echo '<div style="margin-bottom:0.5rem;"><a target="_blank" href="'.$archive[2].'">Renaissance Archive of the School of Music (University of Illinois at Urbana-Champaign)</a></div>';                    
              endif;  
            ?>  
          <?php elseif($propertyData['property']->term() == 'alamire:description'):?>  
            <div style="margin-bottom:0.5rem;"><?php echo $value;?></div>
          <?php elseif($propertyData['property']->term() == 'alamire:bibliographicCitation'):
            if($values['alamire:bibliographicCitation']['values']):
              $cites = $values['alamire:bibliographicCitation']['values'];
              $sort_cites = array();
              
              foreach($cites as $cite):
                $cite = $cite.'';
                if(str_contains($cite,"$$")):
                  $cite = explode("$$",$cite);     
                  if(!empty($cite[5])):
                    $sort_cites[trim($cite[5])] = $cite;
                  else:
                    $sort_cites[] = $cite;
                  endif;
                else:
                   //compos
                   $cite = explode(" ",$cite);
                   array_shift($cite);
                   echo '<div style="margin-bottom:0.5rem;">'.implode(" ",$cite)."</div>";
                endif;  
              endforeach;
              ksort($sort_cites);

              foreach($sort_cites as $cite):               
                //manu                          
                if(!empty($cite[2]) && !empty($cite[0])):
                  $cite[0] = str_replace("[","",$cite[0]);
                  $cite[0] = str_replace("]","",$cite[0]);
                  if(!empty(trim($cite[3]))):
                    $label = '<a href="'.$cite[3].'">'.$cite[2].'</a>';
                  else:
                    $label = trim($cite[2]);
                  endif;
                  echo '<div style="margin-bottom:0.5rem;"><strong>'.trim($cite[0])."</strong> ".$label;
                  if(!empty($cite[4])):
                    echo $cite[4];
                  endif;  
                  echo "</div>";
                elseif(!empty($cite[2]) && empty($cite[0])):
                  if(!empty(trim($cite[3]))):
                    $label = '<a href="'.$cite[3].'">'.trim($cite[2]).'</a>';
                  else:
                    $label = trim($cite[2]);
                  endif; 
                  //$label = trim($cite[2]);
                  echo '<div style="margin-bottom:0.5rem;">'.$label.$cite[4]."</div>";
                else:
                  echo '<div style="margin-bottom:0.5rem;">'.trim($cite[0]).$cite[4]."</div>";
                endif;
              endforeach;  
                  
            endif;
            $values['alamire:bibliographicCitation']['values'] = "";
          ?>   
          <?php elseif($propertyData['property']->term() == 'alamire:furtherBibliography'):
            if($values['alamire:furtherBibliography']['values']):
              $cites = $values['alamire:furtherBibliography']['values'];
              $sort_cites = array();
              
              foreach($cites as $cite):
                $cite = $cite.'';
                if(str_contains($cite,"$$")):
                  $cite = explode("$$",$cite);     
                  if(!empty($cite[5])):
                    $sort_cites[trim($cite[5])] = $cite;
                  else:
                    $sort_cites[] = $cite;
                  endif;
                else:
                   //compos
                   $cite = explode(" ",$cite);
                   array_shift($cite);
                   echo '<div style="margin-bottom:0.5rem;">'.implode(" ",$cite)."</div>";
                endif;  
              endforeach;
              ksort($sort_cites);

              foreach($sort_cites as $cite):               
                //manu                          
                if(!empty($cite[2]) && !empty($cite[0])):
                  $cite[0] = str_replace("[","",$cite[0]);
                  $cite[0] = str_replace("]","",$cite[0]);
                  if(!empty(trim($cite[3]))):
                    $label = '<a href="'.$cite[3].'">'.$cite[2].'</a>';
                  else:
                    $label = trim($cite[2]);
                  endif;
                  echo '<div style="margin-bottom:0.5rem;"><strong>'.trim($cite[0])."</strong> ".$label;
                  if(!empty($cite[4])):
                    echo $cite[4];
                  endif;  
                  echo "</div>";
                elseif(!empty($cite[2]) && empty($cite[0])):
                  if(!empty(trim($cite[3]))):
                    $label = '<a href="'.$cite[3].'">'.trim($cite[2]).'</a>';
                  else:
                    $label = trim($cite[2]);
                  endif; 
                  //$label = trim($cite[2]);
                  echo '<div style="margin-bottom:0.5rem;">'.$label.$cite[4]."</div>";
                else:
                  echo '<div style="margin-bottom:0.5rem;">'.trim($cite[0]).$cite[4]."</div>";
                endif;
              endforeach;  
                  
            endif;
            $values['alamire:furtherBibliography']['values'] = "";
          ?>   
          <?php elseif($propertyData['property']->term() == 'alamire:relatedManuscript'):
            //library record
            $relatedManuscript = explode('$$',$value->asHtml());
            echo '<a target="_blank" href="'.$relatedManuscript[0].'">'.$relatedManuscript[2].'</a>';
            ?>  
          <?php elseif($propertyData['property']->term() == 'alamire:relatedManuscriptID'):
            $id = strtolower($value->asHtml());
            echo '<a target="_blank" href="/item/'.$id.'">'.$value->asHtml().'</a>';
            ?>  
          <?php elseif($propertyData['property']->term() == 'alamire:hasVersion'):
            echo '<a target="_blank" href="'.$value->asHtml().'">'.$value->asHtml().'</a>';
            ?>  
          <?php elseif($propertyData['property']->term() == 'alamire:audioLink'):
             if($values['alamire:audioLink']['values']):
              $audios = $values['alamire:audioLink']['values'];
              $array = [];
              foreach($audios as $audio):
                if(str_contains($audio->asHtml(),"spotify")):
                  $array[1] = $audio;          
                elseif(str_contains($audio->asHtml(),"apple")):
                  $array[2] = $audio;                    
                elseif(str_contains($audio->asHtml(),"deezer")):
                  $array[3] = $audio;                    
                elseif(str_contains($audio->asHtml(),"qobuz")):
                  $array[4] = $audio;
                endif;
              endforeach;
              ksort($array);  
              foreach($array as $audio):
                if(str_contains($audio->asHtml(),"spotify")):?>
                  <button data-index="1" class="collapsible button is-small is-primary"><span class="icon"><i class="fa fa-solid fa-music"></i></span><span>Spotify</span></button>                 
                <?php elseif(str_contains($audio->asHtml(),"apple")):?>
                  <button data-index="2" class="collapsible button is-small is-primary"><span class="icon"><i class="fa fa-solid fa-music"></i></span><span>Apple Music</span></button>                
                <?php elseif(str_contains($audio->asHtml(),"deezer")):?>
                  <button data-index="3" class="collapsible button is-small is-primary"><span class="icon"><i class="fa fa-solid fa-music"></i></i></span><span>Deezer</span></button>                
                <?php elseif(str_contains($audio->asHtml(),"qobuz")):?>
                  <a class="button is-small is-primary" target="_blank" href="<?php echo $audio->asHtml();?>"><span class="icon"><i class="fa fa-solid fa-music"></i></i></span><span>Qobuz</span></a>                      
                <?php endif;?> 
              <?php endforeach;?>  
              <?php foreach($audios as $audio):
                if(str_contains($audio->asHtml(),"spotify")):?>
                  <?php $link = $audio->asHtml();?>
                  <?php $link = str_replace("open.spotify.com/","open.spotify.com/embed/",$link);?>
                  <div class="player" data-index="1">
                    <iframe style="border-radius:12px" src="<?php echo $link;?>" width="100%" height="152px" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>     
                  </div>
                <?php elseif(str_contains($audio->asHtml(),"apple")):?>
                  <?php $link = $audio->asHtml();?>
                  <?php $link = str_replace("music.apple.com","embed.music.apple.com",$link);?>
                  <div class="player" data-index="2">
                    <iframe style="border-radius:12px" src="<?php echo $link;?>" width="100%" height="152px" style="top: 0; left: 0; border: 0;" allowfullscreen allow="encrypted-media; fullscreen; clipboard-write;"></iframe>
                  </div>
                <?php elseif(str_contains($audio->asHtml(),"deezer")):?>
                  <?php $link = $audio->asHtml();?>
                  <?php $link = str_replace("https://www.deezer.com/us","https://widget.deezer.com/widget/dark",$link);?>
                  <?php $link = str_replace("https://www.deezer.com/en","https://widget.deezer.com/widget/dark",$link);?>
                 
                  <div class="player" data-index="3">
                    <iframe style="border-radius:12px" src="<?php echo $link;?>" width="100%" height="152px" style="top: 0; left: 0; border: 0;" allowfullscreen allow="encrypted-media; fullscreen; clipboard-write;"></iframe>
                  </div>
               
                <?php endif;?> 
              <?php endforeach;?>  
              <?php $values['alamire:audioLink']['values'] = "";?>
            <?php endif;?>  
          <?php elseif($propertyData['property']->term() == 'alamire:relatedTranscription'):
            $rels = explode("$$",$value->asHtml());
            echo trim($rels[0]);
            ?>      
          <?php elseif($propertyData['property']->term() == 'alamire:relatedFakesimile'):
            $rels = explode("$$",$value->asHtml());
            echo trim($rels[0]);
            ?>  
          <?php elseif($propertyData['property']->term() == 'alamire:relatedText'):
            $rels = explode("$$",$value->asHtml());
            echo trim($rels[0]);
            ?>
          <?php elseif($propertyData['property']->term() == 'alamire:genre'):            
            echo str_replace(";","; ",$value->asHtml());
            ?>  
          <?php elseif($propertyData['property']->term() == 'alamire:relatedAudio'):
            $rels = explode("$$",$value->asHtml());
            echo trim($rels[0]);
            ?>     
          <?php elseif($propertyData['property']->term() == 'alamire:contributors'):  
            $contributor_r = [];
            foreach($values['alamire:contributors']['values'] as $contributor):
              $contributor_r[] = $contributor->asHtml();
            endforeach;
            echo implode(" | ",$contributor_r);
            $values['alamire:contributors']['values'] = [];  
          ?>       
          <?php elseif($propertyData['property']->term() == 'alamire:author'):  
            $author_r = [];
            foreach($values['alamire:author']['values'] as $author):
              $author_r[] = $author->asHtml();
            endforeach;
            echo implode(" | ",$author_r);
            $values['alamire:author']['values'] = [];  
          ?>   
          <?php elseif($propertyData['property']->term() == 'alamire:editor'):  
            $editor_r = [];
            foreach($values['alamire:editor']['values'] as $editor):
              $editor_r[] = $editor->asHtml();
            endforeach;
            echo implode(" | ",$editor_r);
            $values['alamire:editor']['values'] = [];  
          ?>      
          <?php elseif($propertyData['property']->term() == 'alamire:differentiaLabel'):
            $label =  $values['alamire:differentiaLabel']['values'][0]->asHtml();
            $url = '';
            if(!empty($values['alamire:differentiaURL']['values'])):
              $url = $values['alamire:differentiaURL']['values'][0]->asHtml();
            endif;
            $values['alamire:differentiaLabel']['values'] = "";
            $values['alamire:differentiaURL']['values'] = "";
            echo '<a target="_blank" href="'.trim($url).'">'.trim($label).'</a>';
            ?>                   
          <?php elseif($propertyData['property']->term() == 'alamire:relatedComposition'):?>
            <?php
            //manuscript
            if(str_contains($value->asHtml(),"link:") && $values['alamire:relatedComposition']['values']):
              $rels = $values['alamire:relatedComposition']['values'];

              //make array and sort the whole thing
              $sorted_rels = array();
              foreach($rels as $rel):
                $irel = explode("$$",$rel);
                if(!empty($irel[8])):
                  $sorted_rels[trim($irel[8])] = $irel;
                else:
                  $sorted_rels[] = $irel;
                endif;  
              endforeach;  

              ksort($sorted_rels);
              $rels = $sorted_rels;

              $items = [];
              $tree = [];

              // Build flat list
              foreach ($rels as $rel) {
                  $id = trim($rel[0]);
                  $parentId = trim($rel[1]);

                  $items[$id] = ['value' => $rel, 'children' => []];
              }

              // Assign children to parents
              foreach ($items as $id => &$item) {
                  $parentId = trim($item['value'][1]);
                  if ($parentId && isset($items[$parentId])) {
                      $items[$parentId]['children'][$id] = &$item;
                  } else {
                      // No parent = root
                      $tree[$id] = &$item;
                  }
              }

              echo "<table><tbody>";
              $helper->renderTree($tree, $auth, $helper);
              echo "</tbody></table>";
              
              $values['alamire:relatedComposition']['values'] = "";    
            //composition  
            elseif($values['alamire:relatedComposition']['values']):  
              $rels = explode("##",$value->asHtml());
              $firstrel = array_shift($rels);
              
              $first = explode("$$",$firstrel);
              $first = explode(" ",$first[0]);
              $firstcode = array_shift($first);

              $query = 'property[0][joiner]=and&property[0][property]=216&property[0][type]=eq&property[0][text]='.$firstcode.'&item_set_id[]=&site_id=';
              parse_str($query,$query);

              $first_r = $this->api()->searchOne('items',$query);
              $first_r = $first_r->getContent();
              

              $firstrel = explode(" ",$firstrel);
              array_shift($firstrel);
              $firstrel = implode(" ",$firstrel);
              $firstrel = explode(" $$ ",$firstrel);
             
              if(!empty($firstrel[1])):?>
                <span style="color:#A6361F;"><?php echo $firstrel[1]." ";?></span>
              <?php endif;

              if($first_r):
                echo $first_r->displayTitle();               
              else:
                echo trim(implode(" ",$first));
              endif; 

              if(!empty($firstrel[2])):
                echo " (".$firstrel[2]."v)";
              endif;

              echo "<br>";

              $rels = explode("||",$rels[0]);
             
              foreach($rels as $rel):
                $rel = explode(" ",$rel);
                array_shift($rel);
                $rel = implode(" ",$rel);
                $rel = explode(" $$ ",$rel);
               
                if(!empty($rel[0])):
                  echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
                  if(!empty($rel[1]) && !str_contains($rel[1],"$$")):
                    echo '<span style="font-weight:bold;">'.$rel[1]."</span> ";
                  endif;
                  echo $rel[0];
                  if(!empty($rel[2])):
                    echo " (".$rel[2]."v)";
                  endif;
                  echo "<br>";
                endif;
              endforeach;  
            endif;?>            
          <?php elseif($propertyData['property']->term() == 'alamire:relatedCompoosition'):?>
            <?php 
            //manuscript
            if(str_contains($value->asHtml(),"link:") && $values['alamire:relatedComposition']['values']):
              $rels = $values['alamire:relatedComposition']['values'];

              $sorted_rels = array();
              foreach($rels as $rel):
                $irel = explode("$$",$rel);
                if(!empty($irel[8])):
                  $sorted_rels[trim($irel[8])] = $irel;
                else:
                  $sorted_rels[] = $irel;
                endif;  
              endforeach;  

              ksort($sorted_rels);
              $rels = $sorted_rels;

              // build tree
              $three = [];$lvl1=[];$lvl2=[];$lvl3=[];$lvl4=[];
             
              $i=0;
              foreach($rels as $irel):
                $label = "";$seq = "";
                //page
                if(trim($irel[5]) == "fol."){
                  $label = trim($irel[6]);
                  $label = str_replace("page:","p.",$label);
                }
                else{
                  //fol
                  $label = trim($irel[5]);
                }
                if(trim($irel[4])){
                  $seq = "<span style='width:27px;margin-right:2px;display:inline-block;'>".trim($irel[4]).". </span>";
                }

                if($irel[0] && $irel[1] == "  "):
                  $lvl1[] = "$irel[0]";

                  $query = 'property[0][joiner]=and&property[0][property]=216&property[0][type]=eq&property[0][text]='.trim($irel[2]).'&item_set_id[]=&site_id=';
                  parse_str($query,$query);

                  $first = $this->api()->searchOne('items',$query);
                  $first = $first->getContent();
                  if($first):
                    if($i != 0):
                      echo "</div></div><div class='content-holder'>";
                    else:
                      echo "<div class='content-holder'>";  
                    endif;

                    $cites = $first->value('alamire:creator_display',array('all' => true));
                    $sort_cites = array();
                    foreach($cites as $cite):
                        if(str_contains($cite->asHtml(),"$$")):
                        $cite = explode(" $$ ",$cite->asHtml());    
                        $comps = trim($cite[0]);
                        $comps = explode(" (",$comps);
                        if(!empty($comps[1])):
                            $type = $comps[1];
                            if($type == "credited)"):
                                $comp = $comps[0];
                            elseif($type == "stylistic)"):
                                $comp = "[".$comps[0]."]";
                            elseif($type == "contested)"):
                                $comp = "?".$comps[0];
                            else:
                                $comp = $comps[0];    
                            endif;
                        else:      
                            $comp = $comps[0];
                        endif;   
                        $sort_cites[trim($cite[1])] = $comp;
                        endif;  
                    endforeach;
                    ksort($sort_cites);    
  
                    $composer = implode("; ", $sort_cites);

                    if($composer):
                      $composer = "<strong>".$composer."</strong>: ";
                    endif;  

                    echo  $seq.$composer.'<a style="font-weight:bold;" href="'.$first->url().'">'.$irel[3].'</a>';
                    
                    if(str_contains($irel[7],"http") && $auth):
                      echo '<a target="_blank" style="font-style:italic;" href="'.str_replace(" link: ","",$irel[7]).'">'.$label.'</a>';
                    else:
                      echo $label;
                    endif;  
                  else:
                    if($i != 0):
                      echo "</div></div><div class='content-holder'>";
                    else:
                      echo "<div class='content-holder'>";  
                    endif; 
                    //echo $irel[3]." ".$irel[4]."<br>";
                    echo $irel[3];
                    if(str_contains($irel[7],"http") && $auth):
                      echo '<a target="_blank" style="font-style:italic;" href="'.str_replace(" link: ","",$irel[7]).'">'.$label.'</a>';
                    else:
                      echo $label;
                    endif; 
                  endif;   
                    
                  if($i == 0):
                      echo '<a href="#" class="expand expand-icon"><i class="fa fa-chevron-up"></i></a><div class="hidden-content">';
                    else:
                      echo '<a href="#" class="expand expand-icon"><i class="fa fa-chevron-down"></i></a><div class="hidden-content" style="display:none;">';
                  endif;                  
                else:
                  if(in_array($irel[1],$lvl1)):
                     echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'.$irel[3].' ';
                     if(str_contains($irel[7],"http") && $auth):
                      echo '<a target="_blank" style="font-style:italic;" href="'.str_replace(" link: ","",$irel[7]).'">'.$label.'</a><br>';
                    else:
                      echo $label.'<br>';
                    endif; 
                     $lvl2[] = $irel[0]; 
                  elseif(in_array($irel[1],$lvl2)):
                    echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'.$irel[3].' ';
                    if(str_contains($irel[7],"http") && $auth):
                      echo '<a target="_blank" style="font-style:italic;" href="'.str_replace(" link: ","",$irel[7]).'">'.$label.'</a><br>';
                    else:
                      echo $label.'<br>';
                    endif; 
                    $lvl3[] = $irel[0];
                  elseif(in_array($irel[1],$lvl3)):
                    echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'.$irel[3].' ';
                    if(str_contains($irel[7],"http") && $auth):
                      echo '<a target="_blank" style="font-style:italic;" href="'.str_replace(" link: ","",$irel[7]).'">'.$label.'</a><br>';
                    else:
                      echo $label.'<br>';
                    endif; 
                    $lvl4[] = $irel[0];   
                  else:
                    //first level is a child??
                    if($i != 0):
                      echo "</div></div><div class='content-holder'>";
                    else:
                      echo "<div class='content-holder'>";  
                    endif; 
                    //echo $irel[3]." ".$irel[4]."<br>";
                    echo $irel[3];
                    if(str_contains($irel[7],"http") && $auth):
                      echo '<a target="_blank" style="font-style:italic;" href="'.str_replace(" link: ","",$irel[7]).'">'.$label.'</a>';
                    else:
                      echo $label;
                    endif; 
                  endif;  
                endif;
                $i++;
              endforeach;  
              echo "</div></div>";
              $values['alamire:relatedComposition']['values'] = "";              

            //composition  
            elseif($values['alamire:relatedComposition']['values']):  
              $rels = explode("##",$value->asHtml());
              $firstrel = array_shift($rels);
              
              $first = explode("$$",$firstrel);
              $first = explode(" ",$first[0]);
              $firstcode = array_shift($first);

              $query = 'property[0][joiner]=and&property[0][property]=216&property[0][type]=eq&property[0][text]='.$firstcode.'&item_set_id[]=&site_id=';
              parse_str($query,$query);

              $first_r = $this->api()->searchOne('items',$query);
              $first_r = $first_r->getContent();
              

              $firstrel = explode(" ",$firstrel);
              array_shift($firstrel);
              $firstrel = implode(" ",$firstrel);
              $firstrel = explode(" $$ ",$firstrel);
             
              if(!empty($firstrel[1])):?>
                <span style="color:#A6361F;"><?php echo $firstrel[1]." ";?></span>
              <?php endif;

              if($first_r):
                echo $first_r->displayTitle();               
              else:
                echo trim(implode(" ",$first));
              endif; 

              if(!empty($firstrel[2])):
                echo " (".$firstrel[2]."v)";
              endif;

              echo "<br>";

              $rels = explode("||",$rels[0]);
             
              foreach($rels as $rel):
                $rel = explode(" ",$rel);
                array_shift($rel);
                $rel = implode(" ",$rel);
                $rel = explode(" $$ ",$rel);
               
                if(!empty($rel[0])):
                  echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
                  if(!empty($rel[1]) && !str_contains($rel[1],"$$")):
                    echo '<span style="font-weight:bold;">'.$rel[1]."</span> ";
                  endif;
                  echo $rel[0];
                  if(!empty($rel[2])):
                    echo " (".$rel[2]."v)";
                  endif;
                  echo "<br>";
                endif;
              endforeach;  
            endif;
            ?>    
            
          <?php elseif($propertyData['property']->term() == 'alamire:objectHoldingInstitution'):?>
            <a target="_blank" href="<?php echo $value->asHtml() ?>"><?php echo $value->asHtml() ?></a>            
                   
          <?php else:?>
            <div class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">
                <?php if ($language = $value->lang()): ?>
                <span class="language"><?php echo $language; ?></span>
                <?php endif; ?>
                <?php echo $value->asHtml(); ?>
            </div>
          <?php endif;?>
      <?php endforeach; ?>
      </div>
    </div>
  </div>
<?php endforeach; ?>
