<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
?>

<?php foreach ($templateProperties as $term => $property): ?>
  <?php
  if($property->isPrivate()):
    continue;
  endif;
  $propertyData = '';
  if(isset($values[$property->property()->term()])):
    $propertyData = $values[$property->property()->term()];
  else:
    continue;
  endif;
   
  if($propertyData['property']->term() == "alamire:thumbnail" || $propertyData['alternate_label'] == "Manuscript Label"):
    continue;
  endif;  
  ?>
  <div class="columns is-2">
    <div class="column is-one-fifth">
      <h4 class="has-text-weight-semibold is-6">
      <?php if ($propertyData['alternate_label']): ?>
      <?php echo $escape($propertyData['alternate_label']); ?>
      <?php else: ?>
      <?php echo $escape($translate($propertyData['property']->label())); ?>
      <?php endif; ?>
      <?php if ('term' === $labelInfo): ?>
      <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
      <?php elseif ('vocab' === $labelInfo): ?>
      <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
      <?php endif; ?>
      </h4>
    </div>
    <div class="column is-three-fifths">
      <?php if(($propertyData['property']->term() == "alamire:relatedComposition" && $propertyData['alternate_label'] == "Hierarchy") || $propertyData['property']->term() == "alamire:description"):?>
        <div class="values text">
      <?php else:?>
        <div class="values">
      <?php endif;?>  
      <?php foreach ($propertyData['values'] as $value): ?>
          <?php
          $valueType = $value->type();
          $class = ['value'];
          if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
              $class[] = 'resource';
              $class[] = $escape($value->valueResource()->resourceName());
          } elseif ('uri' == $valueType) {
              $class[] = 'uri';
          }
          if (!$value->isPublic()) {
              $class[] = 'private';
          }
          ?>

          <?php if($propertyData['property']->term() == 'alamire:relatedManuscript'):?>
            <?php 
              $rels = explode("$$",$value->asHtml());
              $query = 'property[0][joiner]=and&property[0][property]=216&property[0][type]=eq&property[0][text]='.$rels[0].'&item_set_id[]=&site_id=';
              parse_str($query,$query);

              $rel = $items = $this->api()->searchOne('items',$query);
              $rel = $rel->getContent();
              if($rel):
                echo '<div style="margin-bottom:0.5rem;">';
                echo '<a href="'.$rel->url().'">'.$rels[0].'</a>';
                if($rels[2] != " link:"):
                  $link = str_replace(" link:","",$rels[2]);
                  $link = str_replace("&amp;","&",$link);
                  echo ' <span style="font-style:italic;border-bottom:1px solid #cc6733"><a target="_blank" href="'.$link.'">'.$rels[1].'</a></span>';
                else:
                  echo ' <span style="font-style:italic;">'.$rels[1].'</span>';
                endif;  
                echo '</div>';
              else:
                //echo $value->asHtml();
              endif; 
            ?>    
          <?php elseif($propertyData['property']->term() == 'alamire:bibliographicCitation'):
            if($values['alamire:bibliographicCitation']['values']):
              $cites = $values['alamire:bibliographicCitation']['values'];
              $sort_cites = array();
              foreach($cites as $cite):
                if(str_contains($cite->asHtml(),"$$")):
                  //manu
                  $cite = explode("$$",$cite->asHtml());
                  if(!empty($cite[2])):
                    $sort_cites[$cite[2]] = $cite;
                  else:
                    $sort_cites[] = $cite;
                  endif;
                  if(!empty($cite[2]) && !empty($cite[0])):
                    echo '<div style="margin-bottom:0.5rem;"><strong>'.trim($cite[0])."</strong> ".trim($cite[2])."</div>";
                  elseif(!empty($cite[2]) && empty($cite[0])):
                    echo '<div style="margin-bottom:0.5rem;">'.trim($cite[2])."</div>";
                  else:
                    echo '<div style="margin-bottom:0.5rem;">'.trim($cite[0])."</div>";
                  endif;  
                else:
                  //compos
                  $cite = explode(" ",$cite->asHtml());
                  array_shift($cite);
                  echo '<div style="margin-bottom:0.5rem;">'.implode(" ",$cite)."</div>";
                endif;  
              endforeach;  
              //ksort($sort_cites);
              foreach($sort_cites as $cite):
                //$rels = explode("$$",$cite->asHtml());
               
              endforeach;            
            endif;
            $values['alamire:bibliographicCitation']['values'] = "";
          ?>   
          <?php elseif($propertyData['property']->term() == 'alamire:hasVersion'):
            echo '<a target="_blank" href="'.$value->asHtml().'">'.$value->asHtml().'</a>';
            ?>  
          <?php elseif($propertyData['property']->term() == 'alamire:relatedTranscription'):
            $rels = explode("$$",$value->asHtml());
            echo trim($rels[0]);
            ?>      
          <?php elseif($propertyData['property']->term() == 'alamire:relatedFakesimile'):
            $rels = explode("$$",$value->asHtml());
            echo trim($rels[0]);
            ?>  
          <?php elseif($propertyData['property']->term() == 'alamire:relatedText'):
            $rels = explode("$$",$value->asHtml());
            echo trim($rels[0]);
            ?>
          <?php elseif($propertyData['property']->term() == 'alamire:relatedAudio'):
            $rels = explode("$$",$value->asHtml());
            echo trim($rels[0]);
            ?>                   
          <?php elseif($propertyData['property']->term() == 'alamire:relatedComposition'):?>

            <?php 
            //manuscript
            if(str_contains($value->asHtml(),"link:") && $values['alamire:relatedComposition']['values']):
              $rels = $values['alamire:relatedComposition']['values'];
              // build tree
              $three = [];$lvl1=[];$lvl2=[];$lvl3=[];$lvl4=[];
             
              $i=0;
              foreach($rels as $rel):
                $irel = explode("$$",$rel);
                if($irel[0] && $irel[1] == "  "):
                  $lvl1[] = "$irel[0]";

                  $query = 'property[0][joiner]=and&property[0][property]=216&property[0][type]=eq&property[0][text]='.trim($irel[2]).'&item_set_id[]=&site_id=';
                  parse_str($query,$query);

                  $first = $this->api()->searchOne('items',$query);
                  $first = $first->getContent();
                  if($first):
                    if($i != 0):
                      echo "</div></div><div class='content-holder'>";
                    else:
                      echo "<div class='content-holder'>";  
                    endif;
                    $composer = implode(", ", $first->value("alamire:creator",["all" => true]));
                    if($composer):
                      $composer = "<strong>".$composer."</strong>: ";
                    endif;  

                    echo  $composer.'<a style="font-weight:bold;" href="'.$first->url().'">'.$irel[3].'</a>';
                    
                    if(str_contains($irel[5],"http")):
                      echo '<a target="_blank" style="font-style:italic;" href="'.str_replace(" link: ","",$irel[5]).'">'.$irel[4].'</a>';
                    else:
                      echo $irel[4];
                    endif;  
                  else:
                    echo "</div></div><div class='content-holder'>"; 
                    echo $irel[3]." ".$irel[4]."<br>";
                  endif;   
                    
                  if($i == 0):
                      echo '<a href="#" class="expand"><i class="fa fa-chevron-up"></i></a><div class="hidden-content">';
                    else:
                      echo '<a href="#" class="expand"><i class="fa fa-chevron-down"></i></a><div class="hidden-content" style="display:none;">';
                    endif;
                                
                  
                else:
                  if(in_array($irel[1],$lvl1)):
                     echo '&nbsp;&nbsp;&nbsp;'.$irel[3].' ';
                     if(str_contains($irel[5],"http")):
                      echo '<a target="_blank" style="font-style:italic;" href="'.str_replace(" link: ","",$irel[5]).'">'.$irel[4].'</a><br>';
                    else:
                      echo $irel[4].'<br>';
                    endif; 
                     $lvl2[] = $irel[0]; 
                  elseif(in_array($irel[1],$lvl2)):
                    echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'.$irel[3].' ';
                    if(str_contains($irel[5],"http")):
                      echo '<a target="_blank" style="font-style:italic;" href="'.str_replace(" link: ","",$irel[5]).'">'.$irel[4].'</a><br>';
                    else:
                      echo $irel[4].'<br>';
                    endif; 
                    $lvl3[] = $irel[0];
                  elseif(in_array($irel[1],$lvl3)):
                    echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'.$irel[3].' ';
                    if(str_contains($irel[5],"http")):
                      echo '<a target="_blank" style="font-style:italic;" href="'.str_replace(" link: ","",$irel[5]).'">'.$irel[4].'</a><br>';
                    else:
                      echo $irel[4].'<br>';
                    endif; 
                    $lvl4[] = $irel[0];   
                  endif;  
                endif;
                $i++;
              endforeach;  
              echo "</div></div>";
              $values['alamire:relatedComposition']['values'] = "";              

            //composition  
            elseif($values['alamire:relatedComposition']['values']):  
              $rels = explode("##",$value->asHtml());
              $first = array_shift($rels);
              
              $first = explode("$$",$first);
              $first = explode(" ",$first[0]);
              $firstcode = array_shift($first);

              $query = 'property[0][joiner]=and&property[0][property]=216&property[0][type]=eq&property[0][text]='.$firstcode.'&item_set_id[]=&site_id=';
              parse_str($query,$query);

              $first_r = $this->api()->searchOne('items',$query);
              $first_r = $first_r->getContent();
              if($first_r):
                echo $first_r->displayTitle()."<br>";
              else:
                echo implode(" ",$first)."<br>";
              endif; 

              $rels = explode("||",$rels[0]);
             
              foreach($rels as $rel):
                $rel = explode(" ",$rel);
                array_shift($rel);
                $rel = implode(" ",$rel);
                $rel = explode(" $$ ",$rel);
                /*$query = 'property[0][joiner]=and&property[0][property]=216&property[0][type]=eq&property[0][text]='.$rel[0].'&item_set_id[]=&site_id=';
                parse_str($query,$query);

                $child = $this->api()->searchOne('items',$query);
                $child = $child->getContent();*/

                if(!empty($rel[0])):
                  echo '&nbsp;&nbsp;&nbsp;'.$rel[0]." (".$rel[1]."v)<br>";
                endif;
              endforeach;  
            endif;
            ?>           
                   
          <?php else:?>
            <div class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">
                <?php if ($language = $value->lang()): ?>
                <span class="language"><?php echo $language; ?></span>
                <?php endif; ?>
                <?php echo $value->asHtml(); ?>
            </div>
          <?php endif;?>
      <?php endforeach; ?>
      </div>
    </div>
  </div>
<?php endforeach; ?>
