<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Form\ForgotPasswordForm $form
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$pageTitle = $plugins->get('pageTitle');
$htmlElement = $plugins->get('htmlElement');

$htmlElement('body')->appendAttribute('class', 'guest forgot-password');
$form->prepare();
?>



<div class="guest-anonymous guest-forgot-password page">
    <h2><?= $translate('Forgot Password') ?></h2>

    <?= $this->messages() ?>

    <?= $this->form()->openTag($form) ?>
        <?= $this->formCollection($form, false) ?>
        <button type="submit"><?= $translate('Send an email to reset the password') ?></button>
    <?= $this->form()->closeTag() ?>

</div>
