<?php
$translate = $this->plugin('translate');
?>
<section class="section" style="padding:0 0 1.5rem 0">
  <div class="container">
    <?php if ($this->heading): ?>
      <h2 class="title is-3 is-family-secondary"><?php echo $this->heading; ?></h2>
    <?php endif; ?>

    <?php if($block->dataValue('text')):?>
      <div class="content">
              <?php echo $block->dataValue('text');?>
      </div>
    <?php endif; ?>

    <?php if($this->resources):?>
    <div class="columns <?php echo $block->dataValue('columns');?> is-multiline">
      <?php
      $headingTerm = $this->siteSetting('browse_heading_property_term', 'alamire:title');
      $bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
      
      foreach ($this->resources as $resource):
          $heading = $resource->value($headingTerm, ['default' => $translate('[Untitled]')]);
          $body = $resource->value($bodyTerm);
          $type = $resource->resourceTemplate();
          if($type):
            $type= $type->label();
          else:
            $type= "Object";
          endif;
      ?>
      <div class="column <?php echo $block->dataValue('columns');?>">
            <?php
              $media = $resource->media();
              if($media):
                if(sizeof($this->resources) <= 2):
                  $mediaurl = $media[0]->thumbnailUrl('large');
                  $mediaurl = str_replace('http:', '', $mediaurl);
                else:
                  $mediaurl = $media[0]->thumbnailUrl('medium');
                  $mediaurl = str_replace('http:', '', $mediaurl);
                endif;
              else:
                $mediaurl = "";
              endif;

              $url = $resource->url();
              $date = '';
            ?>
            <a href="<?php echo $url;?>">
            <div class="card equal-height">
              <div class="card-bg-img-2"
                style="background:url(<?php echo  $mediaurl;?>) no-repeat center 20%;background-size: cover;"
                >
              </div>
              <header class="card-header" style="margin-bottom:0">
                <p class="is-text" style="padding:0.5rem 0">
                    <a href="<?php echo $url;?>"><?php echo $resource->value('alamire:title');?></a>
                </p>
              </header>
            </div>
          </a>
      </div>
      <?php endforeach; ?>
    </div>
    <?php if ($this->linkText):?>
      <div class="has-text-centered">
        <a href="<?php echo '/'.$type.'?q='?>" class="button is-primary">
          <?php echo $this->linkText;?>
        </a>
      </div>
    <?php endif;?>
    <?php endif;?>
  </div>
</section>
